### ISSUE TITLE
I do not approve of this.

### ISSUE THREAD

**Issue by berbb** [complexitydev/PORT-AIO-VIP#1]
You can keep it private but no VIP or selling of my PortAIO.

**Comment by complexitydev** [comment]
It's not selling, just script adjustments for my skype group (that is
free). Your licensing allows for it.

**Comment by complexitydev** [comment]
Also, I'm aware of your GNU license. I'll rename it to just "private" or
something like that. Include two links to your original git as well.

**Comment by berbb** [comment]
Then you know I can easily change the licensing. Make sure it stays public like this.
